### ISSUE TITLE
Working game

### ISSUE THREAD

**Issue by BeardedGrinn** [SchoolOfCode/week-2-hackathon-rock-paper-scissors-team11#1]
```[tasklist]
### Tasks
- [x] Build aray of rock paper scissors
- [x] Prompt user if they want to play the game
- [x] Get computer to randomly select answer
- [x] Prompt user to make a choice
- [x] Determine the outcome between computers choice and users choice
- [x] add way to restart loop
- [x] Add score
- [x] Add a way to do a username
```
