### ISSUE TITLE
Stetch goals

### ISSUE THREAD

**Issue by BeardedGrinn** [SchoolOfCode/week-2-hackathon-rock-paper-scissors-team11#2]
```[tasklist]
### Tasks
- [x] Add lizard, Spock to choices
- [x] Add alternate ending messages depending on if play again
- [x] Make username capitalised
- [x] Add alert for invalid choice
- [ ] Make username only letters, not number or symbols
- [x] Add RPSLS.jpeg to index.html
- [ ] CSS
- [ ] Scoreboard
```
